/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fortnight;


import java.io.IOException;

import com.fortnight.cmdline.Command;
import com.fortnight.cmdline.CreateNapCommand;
import com.fortnight.cmdline.LinkGoogleAccount;
import com.fortnight.cmdline.LinkTodoistAccount;
import com.fortnight.cmdline.Menu;
import com.fortnight.config.Config;


public class App {
	public static Config config;

	public static void init(String args[]) {
		// Load Application Configuration File
    	config = Config.getInstance();
    	String file = "C:\\Users\\yhinge\\Desktop\\Bubu\\fictional-fortnight\\test.properties";
    	if(args.length>0) {
			config.load(args[0]);
    	}else {
			config.load(file);
    	}
	}

    public static void main(String[] args) throws IOException{
    	if(args.length<1) {
    		//System.out.println("Usage: <app> <config-file-path>");
    		//System.exit();
    	}
    	init(args);

    	Menu menu = new Menu(config.getProperty("banner"));
    	menu.addOption("Create a Nap");
    	menu.addOption("Link Your Google Account");
    	menu.addOption("Link Your Todoist Account");
    	menu.addOption("Exit");
    	int selectedOption = menu.run();
    	while(selectedOption!=4) {
			Command command = null;
			switch(selectedOption) {
				case 1:
				command = new CreateNapCommand();
				break;
				case 2:
				command = new LinkGoogleAccount();
				break;
				case 3:
				command = new LinkTodoistAccount();
				break;
				default:
					System.exit(0);
				break;	
			}
			if(command!=null) {
				command.execute();
			}
			selectedOption = menu.run();
    	}
    }

    //Free up resources at the time of shutdown
    public static void shutdown() {
    	
    }
}
